//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.09.25 at 10:41:20 PM EDT 
//


package com.rankminer.audioanalyser.config;

import java.io.File;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for client complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="client">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="name" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="dataInputDirectory" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="dataOutputDirectory" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="dataArchiveDirectory" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="dataErrorArchiveDirectory" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="pollingInterval" type="{http://www.w3.org/2001/XMLSchema}long"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "client", propOrder = {
    "identifier",
    "dataInputDirectory",
    "dataOutputDirectory",
    "dataArchiveDirectory",
    "dataErrorArchiveDirectory",
    "pollingInterval"
})
public class Client extends Thread {

    @XmlElement(required = true)
    protected String identifier;
    @XmlElement(required = true)
    protected String dataInputDirectory;
    @XmlElement(required = true)
    protected String dataOutputDirectory;
    @XmlElement(required = true)
    protected String dataArchiveDirectory;
    @XmlElement(required = true)
    protected String dataErrorArchiveDirectory;
    protected long pollingInterval;

    /**
     * Gets the value of the name property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getIdentifier() {
        return identifier;
    }

    /**
     * Sets the value of the name property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setIdentifier(String value) {
        this.identifier = value;
    }

    /**
     * Gets the value of the dataInputDirectory property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDataInputDirectory() {
        return dataInputDirectory;
    }

    /**
     * Sets the value of the dataInputDirectory property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDataInputDirectory(String value) {
        this.dataInputDirectory = value;
    }

    /**
     * Gets the value of the dataOutputDirectory property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDataOutputDirectory() {
        return dataOutputDirectory;
    }

    /**
     * Sets the value of the dataOutputDirectory property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDataOutputDirectory(String value) {
        this.dataOutputDirectory = value;
    }

    /**
     * Gets the value of the dataArchiveDirectory property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDataArchiveDirectory() {
        return dataArchiveDirectory;
    }

    /**
     * Sets the value of the dataArchiveDirectory property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDataArchiveDirectory(String value) {
        this.dataArchiveDirectory = value;
    }

    /**
     * Gets the value of the dataErrorArchiveDirectory property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDataErrorArchiveDirectory() {
        return dataErrorArchiveDirectory;
    }

    /**
     * Sets the value of the dataErrorArchiveDirectory property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDataErrorArchiveDirectory(String value) {
        this.dataErrorArchiveDirectory = value;
    }

    /**
     * Gets the value of the pollingInterval property.
     * 
     */
    public long getPollingInterval() {
        return pollingInterval;
    }

    /**
     * Sets the value of the pollingInterval property.
     * 
     */
    public void setPollingInterval(long value) {
        this.pollingInterval = value;
    }
    
    @Override
    public void run() {
    	
    	try {
    		// TODO perform directory check for audio file and run the feature vector function.
    		// save the output from processFile function to a file and then move the audio file to archive directory.
    		File [] files = new File(dataInputDirectory).listFiles();
    		for(File file : files) {
    			if(file.isFile()) {
    				// TODO perform process
    			}
    		}
			sleep(pollingInterval);
		} catch (InterruptedException e) {
			e.printStackTrace();
		}
    }
}
